spring:
 application: 
  name: apigateway-server
 cloud:
  gateway:
   routes:
     - id: auth-service
       uri: http://localhost:8081
       predicates:
          - Path=/auth/**
   
     - id: expenses-server
       uri: http://localhost:8082
       predicates:
          - Path=/expenses/**
          
     - id: category-server
       uri: http://localhost:8083
       predicates:
          - Path=/category/**

      
server: 
 port: 8080